### ISSUE TITLE
Error in line 76811 file name: "Mybot.run.exe" Compiled(x86)

### ISSUE THREAD

**Issue by No3Mc** [boludoz/AIO-Mod#10]
Line 76811                                                                                       (File "C\Users\Mypc\Desktop\Github\Aio-Mod\MyBot.run.exe"):
Error: Variable used without being declared.
https://imgur.com/a/gpbwwGx

**Comment by boludoz** [comment]
Thx

**Comment by boludoz** [comment]
you can run it?
