### ISSUE TITLE
Modfunc: getOcrAndCapture changes makes bot too slow

### ISSUE THREAD

**Issue by vDrag0n** [boludoz/AIO-Mod#15]
commit 02647b556eff6dd7b2f871b4722cfcdbb89875ee

Recent Changes adds unnecessary delays and that results in the bot being too slow to see the next button, and other slowdowns.

Is there a reason why the loop got increased from 5 to 10?

**Comment by boludoz** [comment]
The system never worked, for some peculiarity of the bot, it just failed, but now I made a new system, which really works.
