### ISSUE TITLE
on-going issues

### ISSUE THREAD

**Issue by vDrag0n** [boludoz/AIO-Mod#16]
Main Base Issues:
1) when Bot attacks when shield is on, occasionally, the info button will be clicked causing search bases to fail and Bot defaults to cloud search.
Temp fix: reduce waitforclouds maxsearchcount to just 7.
2) For attacking, IsMainPage can be unreliable, which causes attack to cloud one way or another.
temp fix: add waitMainScreen before isMainPage in preparesearch.
3) Opening army window can fail sometimes due to other windows open or not on main screen.
temp fix: add  waitMainScreen before opening army window

BB Issues.
4) BB attack cloud wait does not handle wifi discounnect well, and will sit on clouds due to wifi disconnect.
temp fix: add If $g_bRestart = True Then Return after clicking attack, and after cloud wait.
5) BB always fails to check camp for Minions and possibly other units even if the camp is already filled with minions.
6) BB fails to fill camp after removing troops occasionally.  This is a click fail, i.e. remove 2, click 2, but results in only 1 camp.
7) BB smart attack setting is ignored - CVS attack is always on.

**Comment by boludoz** [comment]
I repeat, thank you.
