### ISSUE TITLE
AttackBB does not deploy Machine, if only Machine is remaining.

### ISSUE THREAD

**Issue by vDrag0n** [boludoz/AIO-Mod#17]
```
AttackBB.au3

Local $aBBAttackBar = MachineKick($aAvailableTroops)

If $aBBAttackBar = -1 Then Return

```
This affects CVS Remain if only machine is left, which happens since CVS doesn't deploy machine.

**Comment by boludoz** [comment]
Excellent bro, thanks.

**Comment by Approchable-123** [comment]
And even if BB is manually deployed the bot fails to activate its ability, says "Machine has no ability".

**Comment by boludoz** [comment]
Ok I will change that a little to make it work, thank you very much, I already solved all the aforementioned bugs, I only need this.
