### ISSUE TITLE
Stop at 3 wins in BB broken

### ISSUE THREAD

**Issue by Approchable-123** [boludoz/AIO-Mod#18]
The bot reads the remaining number of attacks in BB properly initially, but once 3 victories are achieved and no more attacks remain for the day the counter resets and the bot says 3 attacks left and keeps attacking.

**Comment by boludoz** [comment]
ok

**Comment by boludoz** [comment]
It is forcibly set to 3 attacks during testing.

**Comment by boludoz** [comment]
It is forcibly set to 3 attacks during testing, anyway I'm improving the function.

**Comment by vDrag0n** [comment]
commit: 007f96fb3d0909e25726c3e5cc26384b7dbd1f66
Detects 3,2,1 correctly; 
Detects 0 as 3 available.

I adjust the search area from "25, 626, 97, 651" to "25, 626, 97, 640". Seems to work with limited testing.

**Comment by boludoz** [comment]
What is this about?

**Comment by boludoz** [comment]
it occurs to me that it could be the ax.

**Comment by boludoz** [comment]
@vDrag0n I would like you to share your solutions by pull, they really are useful, I would like them to be part.

**Comment by boludoz** [comment]
and @Approchable-123 Approchable-123
