### ISSUE TITLE
commit 6d15f4ac96c514d7cde3f59d3417f519eb76c394 issues

### ISSUE THREAD

**Issue by vDrag0n** [boludoz/AIO-Mod#19]
I'm assuming this is still incomplete since:

1. outside collector logic only has search Mines 
2. obstacle removal is finding actual buildings and not obstacles.
3. occasionally determining resources/trophies in search and base results in zero after adjusting the base diamond (a past issue, but fixed, now reoccurring).

**Comment by boludoz** [comment]
Sorry I forgot to upload a full version, I am really making a lot of changes.

**Comment by boludoz** [comment]
1. I have to rethink the logic of this code.
2. It is a matter of image tolerance, maybe.
3. Apparently it is a cause of missing MyBot.run.txt, it was added again as in the hotfix.
