### ISSUE TITLE
Beta 4.0.5: Line 60 (File : \Attack\SmartZap\drillSearch.au3)

### ISSUE THREAD

**Issue by Approchable-123** [boludoz/AIO-Mod#20]
$aReturnResult[$iResult][3] = Ceiling(Number($g_aDrillLevelTotal[$aReturnResult[$iResult][2]-1]*$g_fDarkStealFactor))
$aReturnResult[$iResult][3] = Ceiling(Number(^ERROR

Error: Array variable has incorrect number of subscripts or subscript dimension range exceeded

**Comment by boludoz** [comment]
grax
