### ISSUE TITLE
Request CC: fail to find send coordinates

### ISSUE THREAD

**Issue by vDrag0n** [boludoz/AIO-Mod#21]
2: D [2020-06-24 10:52:32.089] SearchPixelDonate FindWhite 462|419
2: D [2020-06-24 10:52:32.091] SearchPixelDonate X, Y: 587,261
2: D [2020-06-24 10:52:32.553] SearchPixelDonate FixedMatrixSend 
2: D [2020-06-24 10:52:39.803] My Bot v7.8.3.hotfix - AiO++ MOD v4.0.5 - (MEmu) AutoIt Error: Line 414  (File "C:\Users\\Desktop\AIO-Mod-master\COCBot\Team__AiO__MOD++\functions\Mod's\ModFuncs.au3"):

Click($aClickSend[0], $aClickSend[1], 1, 100, "#0256")
Click($aClickSend[0], ^ ERROR

**Comment by boludoz** [comment]
thx
