### ISSUE TITLE
Lspell recognized as FSpell in Spell Queue

### ISSUE THREAD

**Issue by vDrag0n** [boludoz/AIO-Mod#22]
Attempting to brew and queue Lightning spells. Lightning does get queued correctly, however Bot recognizes as the **double queued** Lightning as freeze in queue, which removes the queued lightning and rebrew the lightning.
```
2: L [2020-06-25 09:19:08.006] Checking Troop tab: 400/400
2: D [2020-06-25 09:19:11.067] Drag | $aCoordArray: 733-208
2: D [2020-06-25 09:19:11.068] Drag detected 2 times!
2: D [2020-06-25 09:19:11.068] Drag | $aCoordArray: 803-26
2: D [2020-06-25 09:19:11.086] Drag (775) x3
2: D [2020-06-25 09:19:11.097] Drag (704) x7
2: L [2020-06-25 09:19:12.564] Checking Spell tab: 12/12
2: D [2020-06-25 09:19:15.247] FSpell | $aCoordArray: 801-219
2: D [2020-06-25 09:19:15.266] FSpell (775) x6
2: L [2020-06-25 09:19:15.268] Some wrong spells in queue (Freeze x6/0)
2: L [2020-06-25 09:19:16.880] Checking Spell tab: 6/12
2: L [2020-06-25 09:19:16.881] Brewing 2nd Army...
2: L [2020-06-25 09:19:21.594] Brewing 6x Lightning Spells
```

**Comment by boludoz** [comment]
I need a comprehensive review of the mod, and be more precise in what I do, or better yet, join the development.

**Comment by boludoz** [comment]
The re brew does it because the red images of the spells are saved in a special file that is inside the lib folder and is encrypted, it can be replaced by a common folder.
