### ISSUE TITLE
getOcrAndCapture causing Search click next timeout

### ISSUE THREAD

**Issue by vDrag0n** [boludoz/AIO-Mod#23]
The NEXT button times out due to checkAttackDisable x2 searching getAttackDisable 3x using getOcrAndCapture 8x

Reducing Local $iMax from 8 to 3 prevents this.

Is searching empty OCR 8 times necessary?

**Comment by boludoz** [comment]
It was necessary, not now, seeing the official hotfix, I discovered that the lack of mybot.run.txt causes problems in the OCR.

**Comment by boludoz** [comment]
Give me your email if you want to join the development.

**Comment by boludoz** [comment]
Deleted func, it not is necessary now.
