### ISSUE TITLE
getOcrAndCapture error newest version

### ISSUE THREAD

**Issue by TheKushStyle** [boludoz/AIO-Mod#24]
Hi.
With 7ef5426da5b7028b5673e8aafbafd95b983127d9 GetOcrAndCapture got removed from ' COCBot/Team__AiO__MOD++/functions/Mod's/ChatActions/IAChat.au3'

This function is still in use in  'COCBot/functions/Read Text/GetOcr.au3' on line 111 and will cause a crash when starting the bot.

![image](https://user-images.githubusercontent.com/7372555/85846411-13088100-b7a6-11ea-896b-f2805dbd2c63.png)

**Comment by boludoz** [comment]
Sorry, it was a poorly uploaded file, fixing.
