### ISSUE TITLE
commit ab68b15 : Line 176 File (functions\Attack\BuilderBase\AttackBB.au3)

### ISSUE THREAD

**Issue by Approchable-123** [boludoz/AIO-Mod#26]
$g_iAndroidSuspendModeFlags = $iAndroidSuspendModeFlagsLast 
$g_iAndroidSuspendModeFlags = ^ ERROR
 
Error: Variable used without being declared

**Comment by Dissociable** [comment]
I have fixed this if the #25 pull request gets merged.
