### ISSUE TITLE
Builder Base issues

### ISSUE THREAD

**Issue by Dissociable** [boludoz/AIO-Mod#31]
1. Smart Attack Drop order not working:
```
2: L [] Deploying Troops in Custom Order.
2: L [] Deploying CannonCart x3
2: L [] SuperPekka, (156,677), Slot: 1, Count: 1
```
it had to drop SuperPekka first.

2. Smart Attack not Dropping Battle Machine

The issues are not fixed till boludoz@a1d69fbc8289e50636b1e25033f0125cef4214af commit

**Comment by Dissociable** [comment]
Why closed? not yet fixed! have you even tested then closed the issue?

**Comment by boludoz** [comment]
sorry, that comment doesn't have to do with the fix.

**Comment by Dissociable** [comment]
> 
> 
> sorry, that comment doesn't have to do with the fix.

What?! why?

**Comment by boludoz** [comment]
I am referring to the git comment quoted

**Comment by boludoz** [comment]
It has nothing to do with the smart CSV attack. I will try to see the problem.

**Comment by Dissociable** [comment]
> 
> 
> It has nothing to do with the smart CSV attack. I will try to see the problem.

I didn't said it's CSV! it's just the Smart Attack, not the CSV attack.

**Comment by boludoz** [comment]
The only thing that smart attack and csv attack have in common is the attack bar and the external drop points.

**Comment by boludoz** [comment]
I would like to know the relationship between @vDrag0n comment and the bug.
