### ISSUE TITLE
bb csv issue

### ISSUE THREAD

**Issue by xczsonn** [boludoz/AIO-Mod#38]
:01:16] Selected Raged Barbarian X:| 166 Y:| 564
[오후 4:01:16] Incorrect troop On Camp 1 - Barbarian -> Minion
[오후 4:01:16] Click Switch Button 0
[오후 4:01:19] Selected Beta Minion X:| 334 Y:| 551
[오후 4:01:19] Incorrect troop On Camp 5 - Minion -> Barbarian
[오후 4:01:19] Click Switch Button 4
[오후 4:01:22] Selected Raged Barbarian X:| 166 Y:| 564
[오후 4:01:22] Incorrect troop On Camp 1 - Barbarian -> Minion
[오후 4:01:22] Click Switch Button 0
[오후 4:01:25] Selected Beta Minion X:| 334 Y:| 551
[오후 4:01:25] Incorrect troop On Camp 5 - Minion -> Barbarian
[오후 4:01:25] Click Switch Button 4
[오후 4:01:29] Selected Raged Barbarian X:| 166 Y:| 564
[오후 4:01:29] Incorrect troop On Camp 1 - Barbarian -> Minion
[오후 4:01:29] Click Switch Button 0
[오후 4:01:32] Selected Beta Minion X:| 334 Y:| 551
[오후 4:01:32] Incorrect troop On Camp 5 - Minion -> Barbarian

why??
i want to using midrop
but bot compel barb

**Comment by Dissociable** [comment]
Thanks for the report.
Fixed it by ac82d34907dac1b3bef595bfb8065e4684905dfd .
Wait for the release.
