### ISSUE TITLE
Version 4.1.1: Drop Trophies

### ISSUE THREAD

**Issue by Approchable-123** [boludoz/AIO-Mod#39]
The bot keeps clicking boost army or boost heroes (above the troop list while attacking) while trying to drop trophies. It does work normally a few times but fails a lot more. Happens with and without heroes.

**Comment by boludoz** [comment]
ok, does this happen in the normal version?

**Comment by Dissociable** [comment]
> 
> 
> The bot keeps clicking boost army or boost heroes (above the troop list while attacking) while trying to drop trophies. It does work normally a few times but fails a lot more. Happens with and without heroes.

Fixed it by Dissociable@53faa50368c9c921aae8131b8728eb2dc540e261 .
