### ISSUE TITLE
Could not get count for Machine in slot 5

### ISSUE THREAD

**Issue by No3Mc** [boludoz/AIO-Mod#4]

**Comment by boludoz** [comment]
Bb csv attack is BETA.

**Comment by boludoz** [comment]
fixed in new version, you can test from last git?

**Comment by No3Mc** [comment]
@boludoz ya sure I'll test it after like a day or two. Travelling rn.

**Comment by No3Mc** [comment]
Moved to https://github.com/boludoz/AIO-Mod/issues/10
