### ISSUE TITLE
Problem with starting bot

### ISSUE THREAD

**Issue by Luferi00** [boludoz/AIO-Mod#40]
Every time I want to start the bot, it happens an error.
It says:

Line 73173  (File "C:\Users\Luis\Desktop\MyBot.run(7)\MyBot.run.exe"):

Error: Variable subscript badly formatted.

Thanks for help!

**Comment by Dissociable** [comment]
> Every time I want to start the bot, it happens an error.
> It says:
> 
> Line 73173 (File "C:\Users\Luis\Desktop\MyBot.run(7)\MyBot.run.exe"):
> 
> Error: Variable subscript badly formatted.
> 
> Thanks for help!

Hello, 
We need more informations like the version you trying to open and we need you to run the bot by the .au3 file instead of .exe

**Comment by Luferi00** [comment]
Hey,
I am using the version: MyBot v7.8.3++ AIO Mod v4.1.1
So I started the bot by the .au3 file and this happened:
![error mybot](https://user-images.githubusercontent.com/69039270/89407828-c22e6580-d71f-11ea-81a0-efe6009b8339.png)

Thanks for reply!

**Comment by Dissociable** [comment]
@Luferi00 
It's the second time that i see someone report that.
9 days ago i tried to fix this issue with e6350f4a6546ade9ececef6087277d295fbebee2 commit.
however, i didn't reproduced it so i'm not yet completely sure that it's fixed or not.
You can let us know that by:
Open C:\Users\Luis\Desktop\MyBot.run (7)\COCBot\functions\Config\readConfig.au3 file in a text editor (Even Notepad)
Then Go to line 532 and replace that with:
`If $g_aiClanCastleSiegeWaitType[$i] < $eSiegeMachineCount And $g_aiClanCastleSiegeWaitType[$i] >= 0 Then $g_aiCCSiegeExpected[$g_aiClanCastleSiegeWaitType[$i]] = 1`
That's all, open the .au3 file again.
I'm waiting for your reply :)

**Comment by Luferi00** [comment]
Hey, thanks for the fast reply!
I changed it, started the bot and it worked! Running without problems :)
