### ISSUE TITLE
Version 4.2.5 : OCR issues

### ISSUE THREAD

**Issue by Approchable-123** [boludoz/AIO-Mod#44]
I´m running multiple instances and only a few of them seem to have this OCR issue. Tried restarting bot and pc with no effect.

```
DEBUG | ERROR on GetOCRCurrent
Cannot find Army Window...
DEBUG | ERROR on GetCurrentArmy

```
The bot has several page errors and then proceeds to restart the emulator, which seems to solve the issue temporarily but after running for some duration or performing an account switch the same errors pops up. The bot does work but this error loop slows down the no.of attacks significantly.   

Setup info: Windows 10 latest build, Memu 6.2.7, Multi instances with account switching enabled.

Let me know if any additional files are required to debug.

**Comment by boludoz** [comment]
I think it was fixed.
