### ISSUE TITLE
Version 4.2.5: BB Attack Troop Selection

### ISSUE THREAD

**Issue by Approchable-123** [boludoz/AIO-Mod#45]
Running the bot with select CSV based on base enabled in BB attack.

When the bot is using the GiBomCart CSV it selects proper troops in all the camps but when it uses the Midrop CSV (weak air) the bot fails to select dropships and uses a full minion army (6 camp space).

**Comment by boludoz** [comment]
Thank you.

**Comment by Approchable-123** [comment]
In 4.2.6 the troop selection seems to be broken completely. The bot fails to properly select troops for even the GiBomCart CSV and ends up attacking with full barbs.

**Comment by boludoz** [comment]
For the configuration to take effect you must start the bot first.

**Comment by boludoz** [comment]
Thanks for your report.
