### ISSUE TITLE
Version 4.2.6  gets stuck zooming out

### ISSUE THREAD

**Issue by KiRZeN** [boludoz/AIO-Mod#47]
Hello, the bot gets stuck zooming out after an attack and does not advance. Thank you.

 

https://ibb.co/Q99nkTG

**Comment by KiRZeN** [comment]
Tell you that after activating winapi the bot continues to get stuck but at least it already restarts the coc and continues to work without problems.

**Comment by KiRZeN** [comment]
After a few days testing configurations I have discovered which option is causing the bot's jams, it is the following: https://ibb.co/6g2XCWD when disabling this option the bot worked perfectly again.

**Comment by boludoz** [comment]
Thanks for your report.
