### ISSUE TITLE
Version 4.2.7 - Cannot find Army Window

### ISSUE THREAD

**Issue by KiRZeN** [boludoz/AIO-Mod#49]
The bot gets stuck in Cannot find Army Window, it restarts when it reaches the number of errors but it is not solved.

https://ibb.co/4mQQbjq

**Comment by KiRZeN** [comment]
Using default ADB solves the error, therefore it is something with WinAPI, thanks for the work of this mod.

**Comment by boludoz** [comment]
Did you make sure to delete the bot before putting in the new files?

**Comment by boludoz** [comment]
We have changed a library to add compatibility with winapi, maybe that's it.

**Comment by boludoz** [comment]
I have changed the tolerances and improved the images with a new method that detects the color difference, we will try.

**Comment by KiRZeN** [comment]
> Did you make sure to delete the bot before putting in the new files?

Yes, completely deleting the folder from the previous version of the bot still happens, in this latest version 4.2.8 the problem continues.

**Comment by KiRZeN** [comment]
Testing Train()
[11:50:15] Waiting for Main Screen
[11:50:15] waitMainScreen ChkObstl Loop = 0, ExitLoop = 0
[11:50:15] waitMainScreen, Expected: 7ABDDF, Tolerance: 25 at X,Y: 278,9 Found: 7ABDDF
[11:50:15] Screen cleared, WaitMainScreen exit
[11:50:15] IsMain, Expected: 7ABDDF, Tolerance: 25 at X,Y: 278,9 Found: 7ABDDF
[11:50:15] Waiting for DLL async function | Func : SearchMultipleTilesBetweenLevels Params :  0x3E0512FE -QzpcTXlCb3QucnVuIEFJT1xDT0NCb3RcVGVhbV9fQWlPX19NT0QrK1xJbWFnZXNcT2JzdGFjbGVz
 FV 0 FV 0 1000 Default Default Default
[11:50:16] No Button found
[11:50:16] ClickAway ? True
[11:50:17] **Main Window OK**
[11:50:17] DMDecodeMatch | No matches : You're using Dissociable.Matching.dll but it's renamed to DissociableMatching.dll, Please rename it to Dissociable.Matching.dll
[11:50:17] DMDecodeMatch | No matches : You're using Dissociable.Matching.dll but it's renamed to DissociableMatching.dll, Please rename it to Dissociable.Matching.dll
[11:50:17] DMDecodeMatch | No matches : You're using Dissociable.Matching.dll but it's renamed to DissociableMatching.dll, Please rename it to Dissociable.Matching.dll
[11:50:18] DMDecodeMatch | No matches : You're using Dissociable.Matching.dll but it's renamed to DissociableMatching.dll, Please rename it to Dissociable.Matching.dll
 

 

 

 

 

Testing Train()
2: L [2020-10-08 11:50:15.131] Waiting for Main Screen
2: D [2020-10-08 11:50:15.132] waitMainScreen ChkObstl Loop = 0, ExitLoop = 0
2: D [2020-10-08 11:50:15.145] waitMainScreen, Expected: 7ABDDF, Tolerance: 25 at X,Y: 278,9 Found: 7ABDDF
2: D [2020-10-08 11:50:15.146] Screen cleared, WaitMainScreen exit
2: D [2020-10-08 11:50:15.157] IsMain, Expected: 7ABDDF, Tolerance: 25 at X,Y: 278,9 Found: 7ABDDF
2: D [2020-10-08 11:50:15.715] Waiting for DLL async function | Func : SearchMultipleTilesBetweenLevels Params :  0x3E0512FE -QzpcTXlCb3QucnVuIEFJT1xDT0NCb3RcVGVhbV9fQWlPX19NT0QrK1xJbWFnZXNcT2JzdGFjbGVz
 FV 0 FV 0 1000 Default Default Default
2: D [2020-10-08 11:50:16.790] No Button found
2: L [2020-10-08 11:50:16.797] ClickAway ? True
2: L [2020-10-08 11:50:17.300] **Main Window OK**
2: D [2020-10-08 11:50:17.365] DMDecodeMatch | No matches : You're using Dissociable.Matching.dll but it's renamed to DissociableMatching.dll, Please rename it to Dissociable.Matching.dll
2: D [2020-10-08 11:50:17.647] DMDecodeMatch | No matches : You're using Dissociable.Matching.dll but it's renamed to DissociableMatching.dll, Please rename it to Dissociable.Matching.dll
2: D [2020-10-08 11:50:17.925] DMDecodeMatch | No matches : You're using Dissociable.Matching.dll but it's renamed to DissociableMatching.dll, Please rename it to Dissociable.Matching.dll
2: D [2020-10-08 11:50:18.199] DMDecodeMatch | No matches : You're using Dissociable.Matching.dll but it's renamed to DissociableMatching.dll, Please rename it to Dissociable.Matching.dll
2: L [2020-10-08 11:50:48.989] Cannot find Army Window...
2: D [2020-10-08 11:50:48.991] Page error count increased to 1, source: IsTrainPage
2: L [2020-10-08 11:51:20.923] Cannot find Army Window...
2: D [2020-10-08 11:51:20.924] Page error count increased to 2, source: IsTrainPage
2: D [2020-10-08 11:51:20.927] Error in OpenTrainTab: Cannot find the Army Overview Window
2: D [2020-10-08 11:51:20.934] ******** findMultiple *** START ***
2: D [2020-10-08 11:51:20.935] findMultiple : directory : C:\MyBot.run AIO\imgxml\ArmyOverview\Troops
2: D [2020-10-08 11:51:20.937] findMultiple : sCocDiamond : 23,215|585,215|585,255|23,255
2: D [2020-10-08 11:51:20.939] findMultiple : redLines : 23,215|585,215|585,255|23,255
2: D [2020-10-08 11:51:20.941] findMultiple : minLevel : 0
2: D [2020-10-08 11:51:20.943] findMultiple : maxLevel : 1000
2: D [2020-10-08 11:51:20.944] findMultiple : maxReturnPoints : 0
2: D [2020-10-08 11:51:20.945] findMultiple : returnProps : objectname,objectpoints
2: D [2020-10-08 11:51:20.946] ******** findMultiple *** START ***
2: D [2020-10-08 11:51:21.540] Waiting for DLL async function | Func : SearchMultipleTilesBetweenLevels Params :  0x16050DEE -QzpcTXlCb3QucnVuIEFJT1xpbWd4bWxcQXJteU92ZXJ2aWV3XFRyb29wcw==
 23,215|585,215|585,255|23,255 0 23,215|585,215|585,255|23,255 0 1000 Default Default Default
2: D [2020-10-08 11:51:21.707] findMultiple imgloc search returned no results for 'C:\MyBot.run AIO\imgxml\ArmyOverview\Troops' !
2: D [2020-10-08 11:51:21.709] findMultiple Returned Error or No values : 
2: D [2020-10-08 11:51:21.710] ******** findMultiple *** END ***
2: D [2020-10-08 11:51:21.712] ******** findMultiple *** START ***
2: D [2020-10-08 11:51:21.713] findMultiple : directory : C:\MyBot.run AIO\imgxml\ArmyOverview\Spells
2: D [2020-10-08 11:51:21.714] findMultiple : sCocDiamond : 23,366|585,366|585,400|23,400
2: D [2020-10-08 11:51:21.715] findMultiple : redLines : 23,366|585,366|585,400|23,400
2: D [2020-10-08 11:51:21.716] findMultiple : minLevel : 0
2: D [2020-10-08 11:51:21.717] findMultiple : maxLevel : 1000
2: D [2020-10-08 11:51:21.718] findMultiple : maxReturnPoints : 0
2: D [2020-10-08 11:51:21.719] findMultiple : returnProps : objectname,objectpoints
2: D [2020-10-08 11:51:21.720] ******** findMultiple *** START ***
2: D [2020-10-08 11:51:22.058] findMultiple found : JSpell_100_92.xml
2: D [2020-10-08 11:51:22.075] findMultiple : JSpell_100_92.xml->objectname -> JSpell
2: D [2020-10-08 11:51:22.077] findMultiple : JSpell_100_92.xml->objectpoints -> 55,371|49,371|60,376|64,378|47,376|70,378|65,389|71,372|58,385
2: D [2020-10-08 11:51:22.078] ******** findMultiple *** END ***
2: D [2020-10-08 11:51:30.854] Restore bot window to 860, 0, caller: GUIControl_WM_NCACTIVATE
2: D [2020-10-08 11:51:30.857] HideAndroidWindow: False, False, True, BotMinimizeRestore
2: D [2020-10-08 11:51:30.859] AndroidToFront: Source BotMinimizeRestore->HideAndroidWindow
2: L [2020-10-08 11:51:35.054] Army Window Test
2: L [2020-10-08 11:52:05.264] Cannot find Army Window...
2: D [2020-10-08 11:52:05.270] Page error count increased to 3, source: IsTrainPage
2: D [2020-10-08 11:52:05.870] Restore bot window to 860, 0, caller: GUIControl_WM_NCACTIVATE
2: D [2020-10-08 11:52:05.874] HideAndroidWindow: False, False, True, BotMinimizeRestore
2: D [2020-10-08 11:52:05.877] AndroidToFront: Source BotMinimizeRestore->HideAndroidWindow
2: L [2020-10-08 11:52:25.243] Cannot find Army Window...
2: D [2020-10-08 11:52:25.245] Page error count increased to 4, source: IsTrainPage
2: D [2020-10-08 11:52:25.246] Error in OpenTrainTab: Cannot find the Army Overview Window
2: L [2020-10-08 11:52:26.432] Force random ClickAway.
2: D [2020-10-08 11:52:26.443] IsMain, Expected: 7ABDDF, Tolerance: 25 at X,Y: 278,9 Found: 7ABDDF
2: D [2020-10-08 11:52:27.042] Waiting for DLL async function | Func : SearchMultipleTilesBetweenLevels Params :  0x53051DBE -QzpcTXlCb3QucnVuIEFJT1xDT0NCb3RcVGVhbV9fQWlPX19NT0QrK1xJbWFnZXNcT2JzdGFjbGVz
 FV 0 FV 0 1000 Default Default Default
2: D [2020-10-08 11:52:28.076] No Button found
2: L [2020-10-08 11:52:28.077] ClickAway ? True
2: L [2020-10-08 11:52:28.078] ClickAway(): on X:630, Y:20
2: L [2020-10-08 11:52:28.080] Click 627,22,1,0 #0000 | Away
2: D [2020-10-08 11:52:28.615] IsMain, Expected: 7ABDDF, Tolerance: 25 at X,Y: 278,9 Found: 7ABDDF
2: D [2020-10-08 11:52:29.183] Waiting for DLL async function | Func : SearchMultipleTilesBetweenLevels Params :  0xDE052455 -QzpcTXlCb3QucnVuIEFJT1xDT0NCb3RcVGVhbV9fQWlPX19NT0QrK1xJbWFnZXNcT2JzdGFjbGVz
 FV 0 FV 0 1000 Default Default Default
2: D [2020-10-08 11:52:30.247] No Button found
2: L [2020-10-08 11:52:30.248] ClickAway ? True
2: L [2020-10-08 11:52:30.758] **Main Window OK**
2: D [2020-10-08 11:52:31.371] Personal Break OCR result = 
2: L [2020-10-08 11:52:31.372] Testing Train DONE
2: L [2020-10-08 11:52:40.386] Cannot find Army Window...
2: D [2020-10-08 11:52:40.389] Page error count increased to 5, source: IsTrainPage
2: L [2020-10-08 11:53:12.429] Cannot find Army Window...
2: D [2020-10-08 11:53:12.450] Page error count increased to 6, source: IsTrainPage
2: D [2020-10-08 11:53:12.451] Error in OpenTrainTab: Cannot find the Army Overview Window
2: D [2020-10-08 11:53:12.460] ******** findMultiple *** START ***
2: D [2020-10-08 11:53:12.461] findMultiple : directory : C:\MyBot.run AIO\imgxml\ArmyOverview\Troops
2: D [2020-10-08 11:53:12.462] findMultiple : sCocDiamond : 23,215|585,215|585,255|23,255
2: D [2020-10-08 11:53:12.463] findMultiple : redLines : 23,215|585,215|585,255|23,255
2: D [2020-10-08 11:53:12.466] findMultiple : minLevel : 0
2: D [2020-10-08 11:53:12.468] findMultiple : maxLevel : 1000
2: D [2020-10-08 11:53:12.469] findMultiple : maxReturnPoints : 0
2: D [2020-10-08 11:53:12.471] findMultiple : returnProps : objectname,objectpoints
2: D [2020-10-08 11:53:12.473] ******** findMultiple *** START ***
2: D [2020-10-08 11:53:13.044] findMultiple imgloc search returned no results for 'C:\MyBot.run AIO\imgxml\ArmyOverview\Troops' !
2: D [2020-10-08 11:53:13.045] findMultiple Returned Error or No values : 
2: D [2020-10-08 11:53:13.049] ******** findMultiple *** END ***
2: D [2020-10-08 11:53:13.051] ******** findMultiple *** START ***
2: D [2020-10-08 11:53:13.052] findMultiple : directory : C:\MyBot.run AIO\imgxml\ArmyOverview\Spells
2: D [2020-10-08 11:53:13.055] findMultiple : sCocDiamond : 23,366|585,366|585,400|23,400
2: D [2020-10-08 11:53:13.057] findMultiple : redLines : 23,366|585,366|585,400|23,400
2: D [2020-10-08 11:53:13.058] findMultiple : minLevel : 0
2: D [2020-10-08 11:53:13.059] findMultiple : maxLevel : 1000
2: D [2020-10-08 11:53:13.060] findMultiple : maxReturnPoints : 0
2: D [2020-10-08 11:53:13.061] findMultiple : returnProps : objectname,objectpoints
2: D [2020-10-08 11:53:13.062] ******** findMultiple *** START ***
2: D [2020-10-08 11:53:13.291] findMultiple found : JSpell_100_92.xml
2: D [2020-10-08 11:53:13.292] findMultiple : JSpell_100_92.xml->objectname -> JSpell
2: D [2020-10-08 11:53:13.293] findMultiple : JSpell_100_92.xml->objectpoints -> 55,371|49,371|60,376|64,378|47,376|70,378|65,389|71,372|58,385
2: D [2020-10-08 11:53:13.294] ******** findMultiple *** END ***
2: L [2020-10-08 11:53:47.123] Cannot find Army Window...
2: D [2020-10-08 11:53:47.126] Page error count increased to 7, source: IsTrainPage
2: D [2020-10-08 11:53:47.127] Error in OpenTrainTab: Cannot find the Army Overview Window
2: L [2020-10-08 11:53:48.322] Force random ClickAway.
2: D [2020-10-08 11:53:48.333] IsMain, Expected: 7ABDDF, Tolerance: 25 at X,Y: 278,9 Found: 7ABDDF
2: D [2020-10-08 11:53:48.935] Waiting for DLL async function | Func : SearchMultipleTilesBetweenLevels Params :  0x1C0529F4 -QzpcTXlCb3QucnVuIEFJT1xDT0NCb3RcVGVhbV9fQWlPX19NT0QrK1xJbWFnZXNcT2JzdGFjbGVz
 FV 0 FV 0 1000 Default Default Default
2: D [2020-10-08 11:53:49.977] No Button found
2: L [2020-10-08 11:53:49.978] ClickAway ? True
2: L [2020-10-08 11:53:49.979] ClickAway(): on X:235, Y:15
2: L [2020-10-08 11:53:49.981] Click 236,17,1,0 #0000 | Away
2: D [2020-10-08 11:53:50.527] IsMain, Expected: 7ABDDF, Tolerance: 25 at X,Y: 278,9 Found: 7ABDDF
2: D [2020-10-08 11:53:51.121] Waiting for DLL async function | Func : SearchMultipleTilesBetweenLevels Params :  0x68051596 -QzpcTXlCb3QucnVuIEFJT1xDT0NCb3RcVGVhbV9fQWlPX19NT0QrK1xJbWFnZXNcT2JzdGFjbGVz
 FV 0 FV 0 1000 Default Default Default
2: D [2020-10-08 11:53:52.134] No Button found
2: L [2020-10-08 11:53:52.136] ClickAway ? True
2: L [2020-10-08 11:53:52.655] **Main Window OK**
2: D [2020-10-08 11:53:53.278] Personal Break OCR result = 
2: L [2020-10-08 11:53:53.288] Testing Train DONE

**Comment by boludoz** [comment]
Try now

**Comment by KiRZeN** [comment]
It already works, thank you very much for the quick solution.
