### ISSUE TITLE
Versión 4.3.1 - Error Line 68949 

### ISSUE THREAD

**Issue by KiRZeN** [boludoz/AIO-Mod#50]
good again boldina, thanks for your efforts and those of the AIO ++ team, I am having a problem with the bot, I am attaching an image, if you need more information do not hesitate to ask for it, 

I guess it has to do with the barbarian king level upgrade, thanks again.

 

https://ibb.co/c2wQZBC

**Comment by boludoz** [comment]
Can you download the autoit and run the script with the right button until the error occurs please?

**Comment by KiRZeN** [comment]
Do I run MyBot.run.au3?

**Comment by boludoz** [comment]
yes, please.
Do you remember anything else about how it happened?

**Comment by KiRZeN** [comment]
Yes, I have noticed what happens when the bot tries to improve the heroes, I disable the hero improvement as you recommended and it has not happened again, I also have to tell you that in this latest version 4.3.3 it continues to happen.

**Comment by boludoz** [comment]
Thanks, I'll take a look, I think I know what it is.

**Comment by KiRZeN** [comment]
You're welcome, thanks to you! If I remember correctly, you told me that it was something about the invocation of the action that you were changing.

**Comment by KiRZeN** [comment]
I have not had the errorI have not had the error again in this latest version, having the automatic update of the heroes activated, at the moment everything works perfectly, thank you very much as always for your work. again in this latest version, having the automatic update of the heroes activated, at the moment everything works perfectly, thank you very much as always for your work.
