### ISSUE TITLE
Version 4.3.8 - Error line 69835

### ISSUE THREAD

**Issue by KiRZeN** [boludoz/AIO-Mod#52]
Good boldina, I am attaching an image of an error that just happened to me, from what I can read in the log, it is due to the update of the heroes, I have looked at the previous case, and the error of the line does not match, so It must be a new error, as always I will try to discover the exact moment when it fails, a greeting and thanks.

https://ibb.co/ChL99KH

**Comment by boludoz** [comment]
Hi friend, I need you to install autoit and right click run (x86) and try to cause that error or let the bot just do it. When run as a script it will show the error in the line of code and I will be able to see exactly what is wrong.

**Comment by KiRZeN** [comment]
> Hi friend, I need you to install autoit and right click run (x86) and try to cause that error or let the bot just do it. When run as a script it will show the error in the line of code and I will be able to see exactly what is wrong. Regards.

Hello boldina, I am attaching the image with more information about the error as you asked me, a greeting.

https://ibb.co/wcJshyS

**Comment by boludoz** [comment]
> > Hi friend, I need you to install autoit and right click run (x86) and try to cause that error or let the bot just do it. When run as a script it will show the error in the line of code and I will be able to see exactly what is wrong. Regards.
> 
> Hello boldina, I am attaching the image with more information about the error as you asked me, a greeting.
> 
> https://ibb.co/wcJshyS

I don't know what I wanted to do, thank you.

**Comment by boludoz** [comment]
Try now and close the thread if there are no more errors.

**Comment by KiRZeN** [comment]
As you can see it continues to fail, I am attaching the new image, a greeting.

https://ibb.co/41ZC4vW

**Comment by boludoz** [comment]
Try

**Comment by KiRZeN** [comment]
After two hours that I have been testing, I have not gotten the error again and everything works without problems for the moment, I am sorry I could not have tried it more but during the week I have little time, greetings and as always thank you very much for your work.
