### ISSUE TITLE
GTFO Does Not Train New Troops. 

### ISSUE THREAD

**Issue by RussDev7** [boludoz/AIO-Mod#53]
Am I doing something wrong? The GTFO will properly jump clans in the latest 4.4.3 Patch but it will not train any troops. I get the 95/5 ratio but I'm working with a TH2. Can you add support for the ratio being based of army camp size / custom value? Maybe an option to allow for refill after each jump. Is there no way to detect no troops left to donate?

Here is a screenshot of the bot trying to donate with no troops. Something about -1. Maybe a refill vector?
https://imgur.com/a/1RyDoXm

**Comment by boludoz** [comment]
It's not that they don't train troops, you don't give them respite!

**Comment by boludoz** [comment]
This trains troops in random cycles, it is designed for large villages, unfortunately there is no easy way to do telekinesis by donating and training perfectly.

**Comment by RussDev7** [comment]
> I was curious to enter your github profile, without a doubt it will not be difficult for you to improve this with your knowledge, currently it uses random cycles to train.

I have already created a mod to your file to fit MY needs for it. I'm suggesting this for others in the future. It's not hard to even add a checkbox for the gem feature you wish to add. On line 166 under `CheckIfArmyIsReady()` I have added a feature that always boosts my barracks. You can easily add custom amount features to it. 

For simplistic'ness, this will boost the barracks when in the checking for troops menu.
```
If Not OpenTroopsTab(True, "BoostTrainBuilding()") Then Return
    Local $aBoostBtn = findButton("BoostBarrack")
	If IsArray($aBoostBtn) Then
		ClickP($aBoostBtn)
		_Sleep($DELAYBOOSTBARRACKS1)
		Local $aGemWindowBtn = findButton("GEM")
		If IsArray($aGemWindowBtn) Then
			ClickP($aGemWindowBtn)
			_Sleep($DELAYBOOSTBARRACKS2)
			If IsArray(findButton("EnterShop")) Then
				SetLog("Not enough gems to boost!", $COLOR_ERROR)
			EndIf
		EndIf
	Else
		If IsArray(findButton("BarrackBoosted")) Then
			SetLog("Barracks is already boosted.", $COLOR_SUCCESS)
		Else
			SetLog($sName & "boost button not found!", $COLOR_ERROR)
		EndIf
	EndIf
```

For my use, being such a low TH, I have to constantly retrain troops. Line 213 I added this simple train feature:
```
CloseClanChat()
TrainGTFO()
```
This can all be configured with checkboxes n such. Just some ideas being that your bot in my eyes is mostly being seached and used for the GTFO feature. So to discontinue support for it would hurt your mod. Please take all im saying with a grain of salt. I'm very thankful for your mod, just hoped this could help its future progression.

**Comment by boludoz** [comment]
I thank you.
