### ISSUE TITLE
Tooltips opening slow

### ISSUE THREAD

**Issue by supermopf** [boludoz/AIO-Mod#54]
Hey, I just realized that tooltips are opening very slow or are not showing at all.

It took like 3 seconds to reach this stage:
![image](https://user-images.githubusercontent.com/17810901/118176341-96b87400-b431-11eb-9f1a-8b0660090ccc.png)

I'm using  AIO++ MOD v4.5.2 on Win10 20H2

**Comment by boludoz** [comment]
It is very fast on my pc and that is only an 8th generation i5, I have tried it in an AMD APU and it works well.

**Comment by supermopf** [comment]
I don't have the issue at the normal Version of MBR.

And my Specs are also pretty good:
| Component | Device |
| ------------- | ------------- |
| CPU | Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz   3.60 GHz |
| RAM | 16,0 GB  |
| GPU | Nvidia GeForce GTX 1070 Ti  |

I also disabled Microsoft Defender for the Folder.

Any further idea?

**Comment by boludoz** [comment]
Tooltips are slow, it is by the nature of AutoIt. It seems like a joke, but I have exactly the same configuration.

**Comment by supermopf** [comment]
What a coincidence :D

I just recompiled the executable and now it's working like a charm. 

Have a nice day :)
