### ISSUE TITLE
No resources to Brew all dark elixir spell

### ISSUE THREAD

**Issue by agungyasmi** [boludoz/AIO-Mod#60]
hello, i want to tell you. I don't know if this is a bug or not. but my MBR AIO MOD can't brew all of dark elixir spell

[11:41:53 PM] Open Train Troops Tab
[11:41:58 PM] Open Brew Spells Tab
[11:42:02 PM] No resources to Brew 1x Haste Spell

**Comment by boludoz** [comment]
Oh sorry but I didn't change any of that! I'm sorry but it works for me!
