### ISSUE TITLE
7.9.6 version beta issue

### ISSUE THREAD

**Issue by toxic-dew** [boludoz/AIO-Mod#61]
although it fixed the donation issue, the problem with the smart farm and smart line attack remains... in the smart farm often it can't calculate properly and dumps all of the troops in one location or one side... 
in bb the bot previously hard crashed when trying to build a new building, now it freezes in the same place [ gets stuck in the shop]
it can't upgrade buildings either in bb anymore, it says not enough elixir/gold [triple checked resources to be sure]
![image](https://user-images.githubusercontent.com/58101225/126084017-ac52f2bf-2b6f-487c-b51b-ae02225adddb.png)

**Comment by boludoz** [comment]
xd

**Comment by boludoz** [comment]
thx

**Comment by toxic-dew** [comment]
> thx

btw is there any chat or discord group/server for this mod?

**Comment by boludoz** [comment]
Of course.

**Comment by boludoz** [comment]
https://discord.gg/WZQEa3Kg
