### ISSUE TITLE
Version 4.6.1 - Attack don't recognise TH 10

### ISSUE THREAD

**Issue by clementinise** [boludoz/AIO-Mod#62]
When attacking I aim for TH 10, unfortunately MyBot don't seem to recognize TH 10 and always say `[TH]: -, -`

Here's an image example:
![image](https://user-images.githubusercontent.com/35346472/129446142-e8a4f044-76f4-4903-8b77-a1fd396e49bf.png)

**Comment by clementinise** [comment]
#63

**Comment by boludoz** [comment]
The folks at MyBot are trying to fix the problem, but unfortunately I can't use their files. I'll see how I can fix it.

**Comment by boludoz** [comment]
Thx bro
