### ISSUE TITLE
Auto boost without enable

### ISSUE THREAD

**Issue by vttai96** [boludoz/AIO-Mod#72]
I use version 4.8.1. 
I found boost is buggy, it works when i don't enable it (using default settings). I also tried clearing the time allowed but it still boost. 
Please check it.
![image](https://user-images.githubusercontent.com/52731691/155276376-c3357f21-31a7-4227-8560-1f04c1a22954.png)

**Comment by purogamer** [comment]
oh, Weird, thanks for the report.
