### ISSUE TITLE
switch  account fail

### ISSUE THREAD

**Issue by toomoor** [boludoz/AIO-Mod#75]
bot can't switch account

**Comment by purogamer** [comment]
?

**Comment by boludoz** [comment]
You must be more specific, you tell me that and it is the same as nothing, you must tell me if it is SC ID, shared prefs or what.

**Comment by toomoor** [comment]
SC ID

**Comment by purogamer** [comment]
What happens, what does the bot logs?

**Comment by purogamer** [comment]
check last git, fixed

**Comment by purogamer** [comment]
test last git, tested by me
