### ISSUE TITLE
Switch Account

### ISSUE THREAD

**Issue by toomoor** [boludoz/AIO-Mod#77]
This Error pop up
![Screenshot](https://user-images.githubusercontent.com/46858785/158663810-ac4b1d58-fc72-49af-b499-d95b14bf4022.png)

**Comment by boludoz** [comment]
It's the same as wiping my ass and leaving the paper there, be more descriptive.

**Comment by toomoor** [comment]
when supercell window open this error happening

**Comment by boludoz** [comment]
LOGS?

**Comment by boludoz** [comment]
you can execute this from auto it?

**Comment by toomoor** [comment]
> you can execute this from auto it?

no

**Comment by toomoor** [comment]
> LOGS?

next time i get this error i take screen from logs

**Comment by boludoz** [comment]
Right clic and run (x86), Otherwise I can't help you.

**Comment by toomoor** [comment]
> Right clic and run (x86), Otherwise I can't help you.

ok

**Comment by boludoz** [comment]
If you do this you will see the error in line.

**Comment by toomoor** [comment]
> If you do this you will see the error in line.

can you send to me an example ?

**Comment by toomoor** [comment]
no error pop up

**Comment by toomoor** [comment]
finally i catch error
![image](https://user-images.githubusercontent.com/46858785/159549182-5aabb474-9f2e-4f19-95aa-e8d63d2274d7.png)

**Comment by purogamer** [comment]
thanks bro

**Comment by boludoz** [comment]
Fixed

**Comment by toomoor** [comment]
Thanks for fix
