### ISSUE TITLE
town hall 9 camp army not match with 220 size and dont attack please fix it

### ISSUE THREAD

**Issue by toomoor** [boludoz/AIO-Mod#80]

**Comment by purogamer** [comment]
?

**Comment by toomoor** [comment]
![image](https://user-images.githubusercontent.com/46858785/163977887-5ef58e2d-e016-4797-9a79-8ac861b457b7.png)
logs 
![image](https://user-images.githubusercontent.com/46858785/163978073-c91f423a-bd70-4d42-8ecd-242cc7aa8292.png)
settings

**Comment by toomoor** [comment]
town hall 9 max camps is 220.

**Comment by toomoor** [comment]
i try it 5 time and dont work like before
