### ISSUE TITLE
inactivity builder base

### ISSUE THREAD

**Issue by toomoor** [boludoz/AIO-Mod#83]
i checked it 5 time and bot stay inactive in builder base after first attack

**Comment by toomoor** [comment]
and tonight got this error
![image](https://user-images.githubusercontent.com/46858785/167036751-fc1a559b-b6ba-48cc-8686-06ed9db00fb4.png)

**Comment by toomoor** [comment]
and a lot of inactivity in main village

**Comment by toomoor** [comment]
![image](https://user-images.githubusercontent.com/46858785/167308872-ed27227e-71be-4657-a992-f4db48a02d03.png)
please fix it too
when workshop or spells upgrading this error show

**Comment by toomoor** [comment]
more information for builderbase inactivity
![image](https://user-images.githubusercontent.com/46858785/167309703-7418f236-aca4-437f-b9e6-3869bd84a3de.png)

**Comment by boludoz** [comment]
The bot is getting a big update and is undergoing maintenance.It only works correctly in only farm mode, attack and train.

**Comment by boludoz** [comment]
Pass to me your discord

**Comment by toomoor** [comment]
!༄🌟͜͡𝑨𝒎𝒊𝒓𝒉𝒐𝒔𝒔𝒆𝒊𝒏 ᴬᶜᵉ#8291 

this is my discord

**Comment by Xpl0itU** [comment]
Has this been fixed with the latest update?

**Comment by toomoor** [comment]
no

**Comment by boludoz** [comment]
Sorry, git has been lost and I forgot to fix this, when I'm free I'll fix it.
