### ISSUE TITLE
switching accounts 

### ISSUE THREAD

**Issue by preshan26** [boludoz/AIO-Mod#87]
why doesnt is switch accounts

**Comment by boludoz** [comment]
Why don't you give more details?

**Comment by preshan26** [comment]
sorry waiting for it to try and swap over

**Comment by boludoz** [comment]
Do you use Supercell ID or Shared prefs !?

**Comment by preshan26** [comment]
supercell

**Comment by preshan26** [comment]
[](url![anydesk00001](https://user-images.githubusercontent.com/57241242/169302749-d743bab4-788c-43a9-b934-238dfbdaaccb.png)

**Comment by preshan26** [comment]
not sure where i would find the logs

**Comment by preshan26** [comment]
![anydesk00001](https://user-images.githubusercontent.com/57241242/169305025-42d09fd3-0c4e-4623-875d-b6f7ed0fdd82.png)
