### ISSUE TITLE
[BUG] Cannot Train EDrag

### ISSUE THREAD

**Issue by SalvadorSTM** [boludoz/AIO-Mod#89]
On running func TrainIt(21,1,100)
![image](https://user-images.githubusercontent.com/26339812/169928001-40328235-5fe1-4cf6-8847-1bef14247df9.png)

We expect the Edrag to start training but instead we get an error
![image](https://user-images.githubusercontent.com/26339812/169928035-888be2c3-ab32-45a4-951e-6814fbc91b21.png)

"Camp is FULL"
![image](https://user-images.githubusercontent.com/26339812/169928077-71d62539-6bc0-4a46-871e-ebff125cb07d.png)

Problem line is here
TrainClick.au3 > line 80
![image](https://user-images.githubusercontent.com/26339812/169928464-09438cea-4d9e-442a-829a-786d4267cba6.png)

**Comment by toomoor** [comment]
you can try quick train

**Comment by SalvadorSTM** [comment]
Fixed this issue by swapping the switch case assignments.

original code
```
		Switch $iTrainPos[1]
			Case 0 To 445 + $g_iMidOffsetYFixed
				$iSlotV = 387 + $g_iMidOffsetYFixed ; First ROW
			Case 446 + $g_iMidOffsetYFixed To 550 + $g_iMidOffsetYFixed ; Second ROW
				$iSlotV = 488 + $g_iMidOffsetYFixed
		EndSwitch
```


new code
```
		Switch $iTrainPos[1]
			Case 0 To 445 + $g_iMidOffsetYFixed
				$iSlotV = 488 + $g_iMidOffsetYFixed
			Case 446 + $g_iMidOffsetYFixed To 550 + $g_iMidOffsetYFixed ; Second ROW
				$iSlotV = 387 + $g_iMidOffsetYFixed ; First ROW
		EndSwitch
```

Somehow the rows were mixed up when this was developed. It was checking the wrong [i] icon for yeti and assuming e dragon was greyed out.

**Comment by SalvadorSTM** [comment]
Pull request created https://github.com/boludoz/AIO-Mod/pull/90

**Comment by toomoor** [comment]
can you fix double train for quick train ?
