### ISSUE TITLE
runBuilderBase only works starting from BB and not Main base

### ISSUE THREAD

**Issue by vDrag0n** [boludoz/AIO-Mod#9]
With latest switch base code, BB will work during loop since runBuilderBase runs from the Main Base.

If runBuilderBase runs from the Builder Base then BB loop starts.

> > [3:40:09 PM] [0] Going to Normal Village
> [3:40:13 PM] Trying to locate Main Screen
> [3:40:22 PM] Main Screen located
> [3:40:26 PM] BB Don't detected.

**Comment by boludoz** [comment]
Loop fixed in new version
