### ISSUE TITLE
Clan games bad pixel

### ISSUE THREAD

**Issue by Xpl0itU** [boludoz/AIO-Mod#97]
When doing clan games it says bad pixel at the caravan screen and then tried to zoomout without exiting it, getting stuck

**Comment by SalvadorSTM** [comment]
Yes check pixel is failing for clan games window detection as well as OCR for clan games remaining time and score.

isClanGamesWindow can be improved to detect larger gray area so we get fewer errors than detecting the black area.
![image](https://user-images.githubusercontent.com/26339812/175720947-667e9830-af23-4526-acb0-964559d2a5ef.png)

GetTimesAndScores()
is not detecting any time or score
